# -*- coding: utf-8 -*-
"""高1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zTk44q0BlkN2OVNWIMf4FjwqJr7jTAR
"""

import os
os.mkdir('質數資料夾')
os.chdir('質數資料夾')

n=int(input('請輸入一個整數:'))
s='\n'

if n>=2:
  filename='prime_list.txt'
  file=open(filename,'w+')
  file.write('2')
  file.write(s)
  file.close()

def prime(n):
  for i in range(3,n):
    if n%i==0:
      return False
  return True

for i in range(3,n+1):
  if prime(i):
    filename='prime_list.txt'
    file=open(filename,'a+')
    w=str(i)
    file.write(w)
    if i<n-1:
      file.write(s)
    file.close()

print(os.path.abspath(filename))